use std::fmt::Write as _;

use chrono::{DateTime, Utc};

use crate::event::types::{CompletionStatus, ExecutionId};
use crate::execution::{
    ExecutionState, ExecutionStatus, ExecutionStepContent, RecordedAttachment, StepState,
    StepStatus,
};
use crate::template::types::{InputDefinition, InputType};

/// Render a human-readable Markdown snapshot from the current execution state.
///
/// This is a pure projection: callers must provide an already-replayed
/// [`ExecutionState`]. This function never reads or replays the event log.
#[must_use]
pub fn render_execution_markdown(state: &ExecutionState) -> String {
    let mut output = String::new();

    render_frontmatter(state, &mut output);
    push_fmt(
        &mut output,
        format_args!(
            "\n<!-- Generated by procnote from events.jsonl. Do not edit manually. -->\n\n"
        ),
    );

    let title = state
        .procedure_title
        .as_deref()
        .filter(|title| !title.is_empty())
        .unwrap_or("Untitled procedure");
    let name = state.name.as_deref().filter(|name| !name.is_empty());
    match name {
        Some(name) => push_fmt(
            &mut output,
            format_args!(
                "# {} — {}\n\n",
                escape_inline_text(title),
                escape_inline_text(name)
            ),
        ),
        None => push_fmt(
            &mut output,
            format_args!("# {}\n\n", escape_inline_text(title)),
        ),
    }

    render_summary_table(state, &mut output);
    render_global_notes(state, &mut output);

    push_fmt(&mut output, format_args!("## Steps\n\n"));
    for (index, step_id) in state.step_order.iter().enumerate() {
        if let Some(step) = state.steps.get(step_id) {
            render_step(index + 1, step, &mut output);
        }
    }

    output
}

fn render_frontmatter(state: &ExecutionState, output: &mut String) {
    push_fmt(output, format_args!("---\n"));
    push_fmt(
        output,
        format_args!("procnote_document: execution_snapshot\n"),
    );
    push_fmt(output, format_args!("snapshot_schema_version: 1\n"));
    render_optional_yaml_field(
        output,
        "execution_id",
        state.execution_id.map(|id| id.to_string()).as_deref(),
    );
    render_optional_yaml_field(output, "procedure_id", state.procedure_id.as_deref());
    render_optional_yaml_field(output, "procedure_title", state.procedure_title.as_deref());
    render_optional_yaml_field(
        output,
        "procedure_version",
        state.procedure_version.as_deref(),
    );
    render_optional_yaml_field(output, "name", state.name.as_deref());
    push_fmt(
        output,
        format_args!("status: {}\n", yaml_quote(&status_slug(&state.status))),
    );
    render_optional_yaml_datetime(output, "started_at", state.started_at);
    render_optional_yaml_datetime(output, "finished_at", state.finished_at);
    render_optional_yaml_datetime(output, "updated_at", state.updated_at);
    push_fmt(output, format_args!("---\n"));
}

fn render_summary_table(state: &ExecutionState, output: &mut String) {
    push_fmt(output, format_args!("## Execution summary\n\n"));
    push_fmt(output, format_args!("| Field | Value |\n"));
    push_fmt(output, format_args!("| --- | --- |\n"));
    render_summary_row(output, "Status", &status_label(&state.status));
    render_summary_row(
        output,
        "Procedure",
        &state.procedure_id.as_deref().map_or_else(dash, inline_code),
    );
    render_summary_row(
        output,
        "Version",
        &state
            .procedure_version
            .as_deref()
            .map_or_else(dash, inline_code),
    );
    render_summary_row(
        output,
        "Execution ID",
        &state
            .execution_id
            .map(format_execution_id)
            .map_or_else(dash, |id| inline_code(&id)),
    );
    render_summary_row(output, "Started", &datetime_or_dash(state.started_at));
    render_summary_row(output, "Finished", &datetime_or_dash(state.finished_at));
    render_summary_row(output, "Updated", &datetime_or_dash(state.updated_at));
    push_fmt(output, format_args!("\n"));
}

fn render_global_notes(state: &ExecutionState, output: &mut String) {
    if state.global_notes.is_empty() {
        return;
    }

    push_fmt(output, format_args!("## Notes\n\n"));
    for note in &state.global_notes {
        push_fmt(
            output,
            format_args!(
                "- {} — {}\n",
                note.at.to_rfc3339(),
                escape_inline_text(&note.text)
            ),
        );
    }
    push_fmt(output, format_args!("\n"));
}

fn render_step(number: usize, step: &StepState, output: &mut String) {
    push_fmt(
        output,
        format_args!(
            "### Step {number}: {} {}\n\n",
            escape_inline_text(&step.heading),
            inline_code(&step.id)
        ),
    );

    if let StepStatus::Skipped { at, reason } = &step.status {
        push_fmt(
            output,
            format_args!(
                "> **Skipped at:** {}  \n> **Reason:** {}\n\n",
                at.to_rfc3339(),
                escape_inline_text(reason)
            ),
        );
    }

    for item in &step.content {
        match item {
            ExecutionStepContent::Prose { text } => render_prose(text, output),
            ExecutionStepContent::Checkbox(checkbox) => {
                let marker = if checkbox.checked { "x" } else { " " };
                push_fmt(
                    output,
                    format_args!("- [{marker}] {}\n", escape_inline_text(&checkbox.text)),
                );
                if let Some(toggled_at) = checkbox.toggled_at {
                    push_fmt(
                        output,
                        format_args!("  Toggled at: {}\n", toggled_at.to_rfc3339()),
                    );
                }
                push_fmt(output, format_args!("\n"));
            }
            ExecutionStepContent::InputBlock { inputs } => render_input_block(step, inputs, output),
        }
    }

    render_step_notes(step, output);
}

fn render_prose(text: &str, output: &mut String) {
    push_fmt(output, format_args!("{}\n\n", text.trim()));
}

fn render_input_block(step: &StepState, inputs: &[InputDefinition], output: &mut String) {
    let scalar_inputs: Vec<&InputDefinition> = inputs
        .iter()
        .filter(|definition| definition.input_type != InputType::Attachment)
        .collect();
    if !scalar_inputs.is_empty() {
        push_fmt(output, format_args!("#### Inputs\n\n"));
        push_fmt(
            output,
            format_args!("| ID | Label | Value | Unit | Recorded at |\n"),
        );
        push_fmt(output, format_args!("| --- | --- | --- | --- | --- |\n"));
        for definition in scalar_inputs {
            render_input_row(step, definition, output);
        }
        push_fmt(output, format_args!("\n"));
    }

    let attachment_inputs: Vec<&InputDefinition> = inputs
        .iter()
        .filter(|definition| definition.input_type == InputType::Attachment)
        .collect();
    if !attachment_inputs.is_empty() {
        push_fmt(output, format_args!("#### Attachments\n\n"));
        for definition in attachment_inputs {
            render_attachment_input(step, definition, output);
        }
        push_fmt(output, format_args!("\n"));
    }
}

fn render_input_row(step: &StepState, definition: &InputDefinition, output: &mut String) {
    let recorded = step.inputs.get(&definition.id);
    let value = recorded.map_or_else(dash, |input| inline_code(&input.value));
    let unit = recorded
        .and_then(|input| input.unit.as_deref())
        .or(definition.unit.as_deref())
        .map_or_else(dash, escape_table_cell);
    let recorded_at = recorded.map_or_else(dash, |input| input.at.to_rfc3339());

    push_fmt(
        output,
        format_args!(
            "| {} | {} | {} | {} | {} |\n",
            escape_table_cell(&definition.id),
            escape_table_cell(&definition.label),
            escape_table_cell(&value),
            unit,
            recorded_at
        ),
    );
}

fn render_attachment_input(step: &StepState, definition: &InputDefinition, output: &mut String) {
    let files = step.attachments.get(&definition.id);
    push_fmt(
        output,
        format_args!(
            "- {} {}\n",
            inline_code(&definition.id),
            escape_inline_text(&definition.label)
        ),
    );

    match files {
        Some(files) if !files.is_empty() => {
            for file in files {
                render_attachment(file, output);
            }
        }
        _ => push_fmt(output, format_args!("  - —\n")),
    }
}

fn render_attachment(file: &RecordedAttachment, output: &mut String) {
    push_fmt(
        output,
        format_args!(
            "  - [{}]({})  \n    SHA256: {}  \n    Added at: {}\n",
            escape_link_text(&file.filename),
            escape_link_destination(&file.path),
            inline_code(&file.sha256),
            file.at.to_rfc3339()
        ),
    );
}

fn render_step_notes(step: &StepState, output: &mut String) {
    if step.notes.is_empty() {
        return;
    }

    push_fmt(output, format_args!("#### Notes\n\n"));
    for note in &step.notes {
        push_fmt(
            output,
            format_args!(
                "- {} — {}\n",
                note.at.to_rfc3339(),
                escape_inline_text(&note.text)
            ),
        );
    }
    push_fmt(output, format_args!("\n"));
}

fn render_optional_yaml_field(output: &mut String, name: &str, value: Option<&str>) {
    match value {
        Some(value) => push_fmt(output, format_args!("{name}: {}\n", yaml_quote(value))),
        None => push_fmt(output, format_args!("{name}: null\n")),
    }
}

fn render_optional_yaml_datetime(output: &mut String, name: &str, value: Option<DateTime<Utc>>) {
    match value {
        Some(value) => push_fmt(
            output,
            format_args!("{name}: {}\n", yaml_quote(&value.to_rfc3339())),
        ),
        None => push_fmt(output, format_args!("{name}: null\n")),
    }
}

fn render_summary_row(output: &mut String, field: &str, value: &str) {
    push_fmt(
        output,
        format_args!(
            "| {} | {} |\n",
            escape_table_cell(field),
            escape_table_cell(value)
        ),
    );
}

fn status_slug(status: &ExecutionStatus) -> String {
    match status {
        ExecutionStatus::Pending => "pending".to_string(),
        ExecutionStatus::Active => "active".to_string(),
        ExecutionStatus::Finished(completion) => completion_status_slug(completion).to_string(),
    }
}

fn status_label(status: &ExecutionStatus) -> String {
    match status {
        ExecutionStatus::Pending => "Pending".to_string(),
        ExecutionStatus::Active => "Active".to_string(),
        ExecutionStatus::Finished(completion) => match completion {
            CompletionStatus::Pass => "Pass".to_string(),
            CompletionStatus::Fail => "Fail".to_string(),
            CompletionStatus::Aborted => "Aborted".to_string(),
        },
    }
}

const fn completion_status_slug(status: &CompletionStatus) -> &'static str {
    match status {
        CompletionStatus::Pass => "pass",
        CompletionStatus::Fail => "fail",
        CompletionStatus::Aborted => "aborted",
    }
}

fn datetime_or_dash(value: Option<DateTime<Utc>>) -> String {
    value.map_or_else(dash, |value| value.to_rfc3339())
}

fn format_execution_id(id: ExecutionId) -> String {
    id.to_string()
}

fn dash() -> String {
    "—".to_string()
}

fn yaml_quote(value: &str) -> String {
    let mut quoted = String::from("\"");
    for c in value.chars() {
        match c {
            '\\' => quoted.push_str("\\\\"),
            '"' => quoted.push_str("\\\""),
            '\n' => quoted.push_str("\\n"),
            '\r' => quoted.push_str("\\r"),
            '\t' => quoted.push_str("\\t"),
            _ => quoted.push(c),
        }
    }
    quoted.push('"');
    quoted
}

fn inline_code(value: &str) -> String {
    if value.is_empty() {
        return "``".to_string();
    }

    let longest_run = longest_backtick_run(value);
    let fence = "`".repeat(longest_run + 1);
    if value.starts_with('`') || value.ends_with('`') {
        format!("{fence} {value} {fence}")
    } else {
        format!("{fence}{value}{fence}")
    }
}

fn longest_backtick_run(value: &str) -> usize {
    value
        .chars()
        .fold((0usize, 0usize), |(longest, current), c| {
            if c == '`' {
                let current = current + 1;
                (longest.max(current), current)
            } else {
                (longest, 0)
            }
        })
        .0
}

fn escape_inline_text(value: &str) -> String {
    normalize_inline(value)
        .chars()
        .flat_map(|c| match c {
            '\\' | '`' | '*' | '_' | '[' | ']' | '<' | '>' | '|' => vec!['\\', c],
            _ => vec![c],
        })
        .collect()
}

fn escape_table_cell(value: &str) -> String {
    normalize_inline(value).replace('|', "\\|")
}

fn normalize_inline(value: &str) -> String {
    value
        .replace("\r\n", "\n")
        .replace('\r', "\n")
        .replace('\n', "<br>")
}

fn escape_link_text(value: &str) -> String {
    normalize_inline(value)
        .chars()
        .flat_map(|c| match c {
            '\\' | '[' | ']' => vec!['\\', c],
            _ => vec![c],
        })
        .collect()
}

fn escape_link_destination(value: &str) -> String {
    value
        .bytes()
        .fold(String::with_capacity(value.len()), |mut output, byte| {
            match byte {
                b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'/' | b'-' | b'.' | b'_' | b'~' => {
                    output.push(char::from(byte));
                }
                _ => push_fmt(&mut output, format_args!("%{byte:02X}")),
            }
            output
        })
}

fn push_fmt(output: &mut String, args: std::fmt::Arguments<'_>) {
    output
        .write_fmt(args)
        .expect("writing to a String should never fail");
}

#[cfg(test)]
#[expect(clippy::unwrap_used, reason = "unwrap is acceptable in tests")]
mod tests {
    use std::collections::HashMap;

    use chrono::TimeZone as _;
    use uuid::Uuid;

    use super::*;
    use crate::execution::{ExecutionCheckbox, RecordedInput, RecordedNote};
    use crate::template::types::InputDefinition;

    fn timestamp(seconds: u32) -> DateTime<Utc> {
        Utc.with_ymd_and_hms(2026, 7, 4, 12, 0, seconds)
            .single()
            .unwrap()
    }

    fn sample_state() -> ExecutionState {
        let execution_id = Uuid::parse_str("11111111-1111-4111-8111-111111111111").unwrap();
        let mut state = ExecutionState::new();
        state.execution_id = Some(execution_id);
        state.procedure_id = Some("proc|id".to_string());
        state.procedure_title = Some("Power *Check*".to_string());
        state.procedure_version = Some("1.0.0".to_string());
        state.name = Some("run-one".to_string());
        state.status = ExecutionStatus::Active;
        state.started_at = Some(timestamp(0));
        state.updated_at = Some(timestamp(3));
        state.step_order.push("step-0".to_string());
        state.steps.insert(
            "step-0".to_string(),
            StepState {
                id: "step-0".to_string(),
                heading: "Measure bus".to_string(),
                status: StepStatus::Present,
                content: vec![
                    ExecutionStepContent::Prose {
                        text: "Connect the probe.".to_string(),
                    },
                    ExecutionStepContent::Checkbox(ExecutionCheckbox {
                        id: "step-0/cb-0".to_string(),
                        text: "Probe connected".to_string(),
                        initial_checked: false,
                        checked: true,
                        toggled_at: Some(timestamp(1)),
                    }),
                    ExecutionStepContent::InputBlock {
                        inputs: vec![
                            InputDefinition {
                                id: "voltage".to_string(),
                                label: "Bus | voltage".to_string(),
                                input_type: InputType::Measurement,
                                unit: Some("V".to_string()),
                                options: vec![],
                                expected: None,
                            },
                            InputDefinition {
                                id: "photo".to_string(),
                                label: "Panel photo".to_string(),
                                input_type: InputType::Attachment,
                                unit: None,
                                options: vec![],
                                expected: None,
                            },
                        ],
                    },
                ],
                inputs: HashMap::from([(
                    "voltage".to_string(),
                    RecordedInput {
                        label: "Bus | voltage".to_string(),
                        value: "28.1".to_string(),
                        unit: Some("V".to_string()),
                        at: timestamp(2),
                    },
                )]),
                attachments: HashMap::from([(
                    "photo".to_string(),
                    vec![RecordedAttachment {
                        filename: "panel photo.jpg".to_string(),
                        path: "attachments/abc1234-panel photo.jpg".to_string(),
                        content_type: "image/jpeg".to_string(),
                        sha256: "abc1234".to_string(),
                        at: timestamp(3),
                    }],
                )]),
                notes: vec![RecordedNote {
                    id: "note-1".to_string(),
                    text: "Stable | nominal".to_string(),
                    at: timestamp(3),
                }],
            },
        );
        state
    }

    #[test]
    fn render_snapshot_is_deterministic() {
        let state = sample_state();

        assert_eq!(
            render_execution_markdown(&state),
            render_execution_markdown(&state)
        );
    }

    #[test]
    fn render_snapshot_includes_state_and_escapes_markdown() {
        let markdown = render_execution_markdown(&sample_state());

        assert!(markdown.contains("procnote_document: execution_snapshot"));
        assert!(markdown.contains("# Power \\*Check\\* — run-one"));
        assert!(
            markdown
                .contains("| voltage | Bus \\| voltage | `28.1` | V | 2026-07-04T12:00:02+00:00 |")
        );
        assert!(markdown.contains("[panel photo.jpg](attachments/abc1234-panel%20photo.jpg)"));
        assert!(markdown.contains("Stable \\| nominal"));
        assert!(!markdown.contains("Event history"));
    }
}
